# Generated by Django 5.0.4 on 2026-03-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_property_price_per_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(max_length=225),
        ),
    ]
