# Generated by Django 5.0.4 on 2026-03-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_property_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='favourite',
            new_name='favourited',
        ),
    ]
